apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.2.204